# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='meme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meme_image', models.ImageField(upload_to=b'', verbose_name='https://scontent-ams3-1.xx.fbcdn.net/v/t1.0-9/29101767_1717204321680003_2332367017836806144_n.jpg?oh=0b715285a700bdade3a3041190015a4d&oe=5B434890')),
                ('meme_no', models.IntegerField()),
                ('field_1', models.IntegerField()),
                ('field_2', models.IntegerField()),
                ('field_3', models.IntegerField()),
                ('field_4', models.IntegerField()),
            ],
        ),
    ]
