# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-09 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kartik', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meme',
            name='field_3',
        ),
        migrations.RemoveField(
            model_name='meme',
            name='field_4',
        ),
        migrations.RemoveField(
            model_name='meme',
            name='id',
        ),
        migrations.AlterField(
            model_name='meme',
            name='meme_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
