# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-11 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='meme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meme_no', models.IntegerField()),
                ('field_1', models.IntegerField()),
                ('field_2', models.IntegerField()),
                ('field_3', models.IntegerField()),
                ('field_4', models.IntegerField()),
            ],
        ),
    ]
