# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-11 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rushikesh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='meme_image',
            field=models.ImageField(default='https://scontent-ams3-1.xx.fbcdn.net/v/t1.0-9/29101767_1717204321680003_2332367017836806144_n.jpg?oh=0b715285a700bdade3a3041190015a4d&oe=5B434890', upload_to=b'', verbose_name='https://scontent-ams3-1.xx.fbcdn.net/v/t1.0-9/29101767_1717204321680003_2332367017836806144_n.jpg?oh=0b715285a700bdade3a3041190015a4d&oe=5B434890'),
            preserve_default=False,
        ),
    ]
